"""Shared defaults for the Voice channel."""

DEFAULT_WAKE_WORD_ENGINE = "auto"
DEFAULT_AUDIO_DEVICE_INDEX = 1
DEFAULT_SILENCE_THRESHOLD = 500
DEFAULT_SILENCE_DURATION = 1500
DEFAULT_MAX_RECORDING_DURATION = 30
DEFAULT_WAKE_WORD_SENSITIVITY = 0.5
DEFAULT_TTS_VOICE = "en-US-AriaNeural"
