"""Shared defaults for the Voice channel."""
DEFAULT_WAKE_WORD_ENGINE = "auto"
DEFAULT_AUDIO_DEVICE_INDEX = 1
DEFAULT_SILENCE_THRESHOLD = 500
DEFAULT_SILENCE_DURATION = 1500
DEFAULT_MAX_RECORDING_DURATION = 30
DEFAULT_WAKE_WORD_SENSITIVITY = 0.5
DEFAULT_TTS_VOICE = "en-US-AriaNeural"
DEFAULT_SPEAKER_ID = "voice_user"
DEFAULT_ALLOW_FROM = [DEFAULT_SPEAKER_ID]
DEFAULT_SILENT_MODE_ENTER_PHRASES = ["silent mode", "mute yourself"]
DEFAULT_SILENT_MODE_EXIT_PHRASES = ["silent mode", "unmute yourself", "listen to me again", "listen again"]
